### PR TITLE
data-cfsync added + removed customer info when logged off

### PR DESCRIPTION
**Pull request by rafalolszewskii**

### CODE REVIEW

**Comment by rafalolszewskii** [comment]
`data-cfasync` is required for script tags since Rocket Loader will prevent our scripts from running.

Also, no idea why, but the cookie value stays the same, but when refreshing the page - messages are getting lost.

**Comment by lukaszsadowski1** [comment]
What cookie value exacly?

**Comment by rafalolszewskii** [comment]
User key, which is set to __ca__chat cookie. It is needed for widget to function as it should. If we don't have this cookie - user after refreshing webpage will "loose" his conversation, as well as his history of page views etc. etc. Basically, new user will be created for him.

**Comment by rafalolszewskii** [comment]
There's also a missing JS library `modules/userengage/assets/ajaxcart-override.js`

**Comment by rafalolszewskii** [comment]
Also, it seems that cookies fixed itself 😃

**Pull request merged**
